language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coverage==5.3
  - pip install pylint

script:
    - coverage run
    - pylint *py

after_success:
  - bash <(curl -s https://codecov.io/bash)
